### ISSUE TITLE
Clicking twice on "Check" in the BomWindow "BOM" tab makes problems

### ISSUE THREAD

**Issue by georgschwienbacher** [coolOrangeLabs/powerGateTemplate#190]
Apply the same solution for pG Template here like we did in https://github.com/coolOrangeProjects/Hauer/commit/ffbf01cdd3c364d55033beb8b976c39534251f31

We had several issues in the past:
+ https://github.com/coolOrangeProjects/Hauer/issues/217#issuecomment-869609641
+ https://github.com/coolOrangeProjects/Grapho-Metronic/issues/37
+ https://github.com/coolOrangeProjects/Hoerbiger/issues/34

**Comment by PatrickGrub** [comment]
Yes, its the very same situation twice and it makes sense to implement it in the template!

**Comment by ThomasRossmeisl** [comment]
Can't fully understand the issue as there is no description, but if this is about bomrows in state "remove" causing errors on repeated presses of the "Check" button the solution would be to use Remove-BomWindowEntity to remove them again.
Generally if an Add-BomWindowEntity is used within the checkfunction the developer also has to add code to the start of the Check-Boms function to remove them again with Remove-BomWindowEntity.

Simply updating them like in Hauer will not fix this issue

**Comment by manuelcassan** [comment]
If there is an `Add-BomWindowEntity` in the `Check-Boms` function it causes issues when clicking the "_Check_" button multiple times. This should be prevented in the `Check-Boms` function by using `Remove-BomWindowEntity` at the beginning of the function and make sure that the entities in the BOM dialog are the same as when the BOM dialog was first opened.

**Comment by StefanNairz** [comment]
The "error" was reproducable by adding the following code to the `Check-Boms` function in `powerGateBomTransfer.ps1`.
`Add-BomWindowEntity -Type BomRow -Properties @{Bom_Number = "test"} -Parent $VaultBom`
Now by multiple clicking the `Check` button we could simulate the "error", it added by every click a new line instead of just one as intended.
First click:
![Check(1)](https://user-images.githubusercontent.com/110519126/190400756-d8b8945f-2983-41e0-8210-9f2a0ba3e8a6.PNG)
Second click:
![Check(2)](https://user-images.githubusercontent.com/110519126/190401465-35f11c47-d5ae-480d-9e08-21bdad476478.PNG)
and so on...
**`In practice this will only happen with removed BomRows.`**

Solution:
We added another foreach loop after the first one in `Check-Boms` to search for BomRows with the status `remove`.
If we can find one it will be removed because by default it will be added again (like in the pictures above).
Solution code:
![SolutionCode](https://user-images.githubusercontent.com/110519126/190403056-af48eec6-3173-4241-984a-323ff3335dbc.PNG)

Note: I'll add the commit link afterwards
